import { create } from 'zustand';

export const useOrderStore = create((set) => ({
    order: {
        companyName: "",
        contactName: "",
        contactEmail: "",
        contactPhone: "",
        location: "",
        orderType: "",
        newOrReorder: "",
        canSize: "",
        brand: "",
        application: "",
        numberOfCans: "",
        endType: "",
        numberOfSleeves: "",
        pakTechType: "",
        numberOfBoxes: "",
        trayType: "",
        bundlesofTrays: "",
        address: "",
        PO: "",
        deliveryMethod: "",
        dunnageType: "",
        date: "",
        copackerEmail: "",
        comments: "",
        PSLfinish: "",
        PSLlength: "",
        filename: "",
    },
    setField: (field, value) => set((state) => ({ order: { ...state.order, [field]: value } })),
}));