import { create } from 'zustand';

export const useOrderStore = create((set) => ({
  order: {
    companyName: '',
    contactName: '',
    contactEmail: '',
    contactPhone: '',
    location: '',
    orderType: '',
    newOrReorder: '',
    canSize: '',
    brand: '',
    application: '',
    numberOfCans: '',
    layersPerPallet: '',
    endType: '',
    numberOfSleeves: '',
    pakTechType: '',
    numberOfBoxes: '',
    trayType: '',
    bundlesofTrays: '',
    address: '',
    PO: '',
    deliveryMethod: '',
    dunnageType: '',
    date: '',
    copackerEmail: '',
    comments: '',
    PSLfinish: '',
    PSLlength: '',
    printingType: '',
    filename: '',
    allinone: false,
    termsOfService: false,
    file: null,
  },
  setField: (field, value) =>
    set((state) => ({ order: { ...state.order, [field]: value } })),
  setFile: (file) => set((state) => ({ order: { ...state.order, file } })),
}));
