import { create } from 'zustand';

export const usePrintedStore = create((set) => ({
  printedvcs: {
    businessName: '',
    contactName: '',
    contactEmail: '',
    PO: '',
    vesselProgram: '',
    orderType: '',
    brand: '',
    varnish: '',
    reorderExpectations: '',
    eoNumber: '',
    canSize: '',
    numberOfPallets: '',
    palletHeight: '',
    liner: '',
    palletsOfEnds: '',
    endIncising: '',
    endTooling: '',
    endLiner: '',
    endNotes: '',
    shipToAddress: '',
    deliveryName: '',
    deliveryPhone: '',
    deliveryEmail: '',
    aptRequired: false,
    shipDate: '',
    customerComments: '',
    landedCost: false,
    submittedBy: '',
    location: '',
    palletContents: 'Printed Cans',
    totalPalletCount: '',
    Shipping: '',
    description: '',
  },
  setField: (field, value) =>
    set((state) => ({ printedvcs: { ...state.printedvcs, [field]: value } })),
}));
